データの読み込み

In [114]:
import pandas as pd

file = "IMG_0569"
df = pd.read_csv(f'data/{file}/position_data.csv')

df = df.set_index("frame")
dt = df

分割(初回のみ)

In [108]:
# import os
# n = 0
# period = []
# data_path = f"data/{file}/split"

# #NaNを含む行の削除
# dt = df.dropna(how='any')

# while n < len(dt.index):
#     days = []
#     for i in range(n,len(dt.index)):
#         num = dt.index[i] + 1
#         if i == len(dt.index)-1:
#             days.append(i)
#             period.append(days)
#             break
#         if dt.index[i+1] == num:
#             days.append(i)
#         else:
#             days.append(i)
#             period.append(days)
#             break
#     n = i+1
# count = 0
# for i in range(len(period)):
#     df = dt.loc[dt.index[period[i]]]
#     if(len(df)) >  1:
#         count +=1
#         if os.path.exists(data_path)==False:
#             os.mkdir(data_path)
#         df.to_csv(f"{data_path}/{file}_Person{count}.csv",encoding="utf-8")

走り出す直前の画像ファイルを特定するための関数

In [117]:
def start_runnig(df_path):
    df = pd.read_csv(df_path,encoding="utf-8")
    df = df.set_index("frame")
    columns = [i for i in df.columns if "NOSE"  in i]
    columns = columns + [i for i in df.columns if "FOOT"  in i]
    columns = [i for i in columns if 'z' not in i]
    data = df[columns]

    #走り出しの定義(画角や撮る方向によって変える必要あり)　→　マーカーとの位置関係を把握必要あり
    df = data.loc[(data["LEFT_FOOT_INDEX_x"] > 0.2) | (data["RIGHT_FOOT_INDEX_x"] > 0.2)]
    df = df.loc[abs(df["LEFT_FOOT_INDEX_x"] - df["RIGHT_FOOT_INDEX_x"]) >= 0.095 ]

    #軸足の検出
    pivot_foot = "RIGHT_FOOT_INDEX_x"
    if list(df["LEFT_FOOT_INDEX_x"])[0] >= list(df["RIGHT_FOOT_INDEX_x"])[0]:
        pivot_foot = "LEFT_FOOT_INDEX_x"
    
    #鼻が軸足よりも前に位置する(走り出すとき、前傾姿勢になる傾向があるため)
    df = df.loc[(df[pivot_foot] < df["NOSE_x"])]
        
    print("軸足 : " + pivot_foot.replace("_INDEX_x",""))
    print("走り出す直前の画像No. : " + str(list(df.index)[0]))
    print("---------"*10)

関数の実行

In [118]:
import os

data_path = f"data/{file}/split"
#ファイル数の取得
n = sum(os.path.isfile(os.path.join(data_path,name)) for name in os.listdir(data_path))

for i in range(n):
    start_runnig(f"data/{file}/split/{file}_Person{i+1}.csv")

軸足 : LEFT_FOOT
走り出す直前の画像No. : 1085
------------------------------------------------------------------------------------------
軸足 : LEFT_FOOT
走り出す直前の画像No. : 3371
------------------------------------------------------------------------------------------

In [111]:
file = "IMG_0895"
df = pd.read_csv(f'data/{file}/position_data.csv')

df = df.set_index("frame")
columns = [i for i in df.columns if "NOSE"  in i]
columns = columns + [i for i in df.columns if "FOOT"  in i]
columns = [i for i in columns if 'z' not in i]
data = df[columns]
data

,NOSE_x,NOSE_y,LEFT_FOOT_INDEX_x,LEFT_FOOT_INDEX_y,RIGHT_FOOT_INDEX_x,RIGHT_FOOT_INDEX_y
frame,,,,,,
1,0.665603,0.322322,0.651370,0.705534,0.672094,0.684397
2,0.665592,0.322307,0.651027,0.705563,0.671840,0.684400
3,0.665591,0.322307,0.650981,0.705492,0.671826,0.683538
4,0.665585,0.322314,0.650702,0.705460,0.671614,0.683480
5,0.665518,0.322435,0.650431,0.705430,0.671506,0.683488
...,...,...,...,...,...,...
5186,NaN,NaN,NaN,NaN,NaN,NaN
5187,NaN,NaN,NaN,NaN,NaN,NaN
5188,NaN,NaN,NaN,NaN,NaN,NaN
5189,NaN,NaN,NaN,NaN,NaN,NaN
5190,NaN,NaN,NaN,NaN,NaN,NaN