In [9]:
import pandas as pd

df = pd.read_csv('sample_submission.csv')
df

            id  target
0            5     0.5
1            6     0.5
2            8     0.5
3            9     0.5
4           11     0.5
...        ...     ...
199995  499983     0.5
199996  499984     0.5
199997  499987     0.5
199998  499994     0.5
199999  499998     0.5

[200000 rows x 2 columns]

In [10]:
df = df.target

In [11]:
d = pd.read_csv("test.csv")
d

,id,cat0,cat1,cat2,cat3,cat4,cat5,cat6,cat7,cat8,...,cont1,cont2,cont3,cont4,cont5,cont6,cont7,cont8,cont9,cont10
0,5,A,F,A,A,F,BI,A,AH,AX,...,0.735690,0.578366,0.723154,0.228037,0.356227,0.551249,0.655693,0.598331,0.359987,0.947489
1,6,A,H,C,A,E,AB,I,F,N,...,0.313703,0.928885,0.516602,0.600169,0.795224,0.248987,0.654614,0.347944,0.565520,0.388580
2,8,A,N,C,A,F,AB,A,AH,BC,...,0.448201,0.424876,0.344729,0.242073,0.270632,0.746740,0.335590,0.341238,0.252289,0.411592
3,9,B,L,C,A,F,BI,A,E,AX,...,0.666092,0.598943,0.561971,0.806347,0.735983,0.538724,0.381566,0.481660,0.348514,0.325723
4,11,A,F,A,B,F,BI,A,AH,I,...,0.772229,0.479572,0.767745,0.252454,0.354810,0.178920,0.763479,0.562491,0.466261,0.585781
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
199995,499983,A,N,A,D,F,BI,A,AF,AX,...,0.361426,0.351946,0.327670,0.205547,0.679195,0.485967,0.319130,0.520681,0.519545,0.427119
199996,499984,B,I,A,B,E,BI,A,AS,S,...,0.551106,0.628843,0.677765,0.624935,0.555306,0.242424,0.700829,0.531728,0.528427,0.922645
199997,499987,A,L,D,A,H,BI,A,AN,J,...,0.812384,0.803348,0.324762,0.665624,0.488447,0.853213,0.578641,0.811941,0.537106,0.531758
199998,499994,A,K,A,C,F,BI,A,R,BM,...,0.811282,0.820635,0.561449,0.797434,0.555089,0.746532,0.369986,0.438712,0.715524,0.381978
199999,499998,A,K,A,A,E,BI,C,AO,BM,...,0.336168,0.270483,0.581868,0.218993,0.553284,0.565213,0.378355,0.547927,0.273595,0.448016

In [12]:
d['target'] = df

In [13]:
d

,id,cat0,cat1,cat2,cat3,cat4,cat5,cat6,cat7,cat8,...,cont2,cont3,cont4,cont5,cont6,cont7,cont8,cont9,cont10,target
0,5,A,F,A,A,F,BI,A,AH,AX,...,0.578366,0.723154,0.228037,0.356227,0.551249,0.655693,0.598331,0.359987,0.947489,0.5
1,6,A,H,C,A,E,AB,I,F,N,...,0.928885,0.516602,0.600169,0.795224,0.248987,0.654614,0.347944,0.565520,0.388580,0.5
2,8,A,N,C,A,F,AB,A,AH,BC,...,0.424876,0.344729,0.242073,0.270632,0.746740,0.335590,0.341238,0.252289,0.411592,0.5
3,9,B,L,C,A,F,BI,A,E,AX,...,0.598943,0.561971,0.806347,0.735983,0.538724,0.381566,0.481660,0.348514,0.325723,0.5
4,11,A,F,A,B,F,BI,A,AH,I,...,0.479572,0.767745,0.252454,0.354810,0.178920,0.763479,0.562491,0.466261,0.585781,0.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
199995,499983,A,N,A,D,F,BI,A,AF,AX,...,0.351946,0.327670,0.205547,0.679195,0.485967,0.319130,0.520681,0.519545,0.427119,0.5
199996,499984,B,I,A,B,E,BI,A,AS,S,...,0.628843,0.677765,0.624935,0.555306,0.242424,0.700829,0.531728,0.528427,0.922645,0.5
199997,499987,A,L,D,A,H,BI,A,AN,J,...,0.803348,0.324762,0.665624,0.488447,0.853213,0.578641,0.811941,0.537106,0.531758,0.5
199998,499994,A,K,A,C,F,BI,A,R,BM,...,0.820635,0.561449,0.797434,0.555089,0.746532,0.369986,0.438712,0.715524,0.381978,0.5
199999,499998,A,K,A,A,E,BI,C,AO,BM,...,0.270483,0.581868,0.218993,0.553284,0.565213,0.378355,0.547927,0.273595,0.448016,0.5

In [14]:
d.to_csv("test.csv")

In [15]:
d

,id,cat0,cat1,cat2,cat3,cat4,cat5,cat6,cat7,cat8,...,cont2,cont3,cont4,cont5,cont6,cont7,cont8,cont9,cont10,target
0,5,A,F,A,A,F,BI,A,AH,AX,...,0.578366,0.723154,0.228037,0.356227,0.551249,0.655693,0.598331,0.359987,0.947489,0.5
1,6,A,H,C,A,E,AB,I,F,N,...,0.928885,0.516602,0.600169,0.795224,0.248987,0.654614,0.347944,0.565520,0.388580,0.5
2,8,A,N,C,A,F,AB,A,AH,BC,...,0.424876,0.344729,0.242073,0.270632,0.746740,0.335590,0.341238,0.252289,0.411592,0.5
3,9,B,L,C,A,F,BI,A,E,AX,...,0.598943,0.561971,0.806347,0.735983,0.538724,0.381566,0.481660,0.348514,0.325723,0.5
4,11,A,F,A,B,F,BI,A,AH,I,...,0.479572,0.767745,0.252454,0.354810,0.178920,0.763479,0.562491,0.466261,0.585781,0.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
199995,499983,A,N,A,D,F,BI,A,AF,AX,...,0.351946,0.327670,0.205547,0.679195,0.485967,0.319130,0.520681,0.519545,0.427119,0.5
199996,499984,B,I,A,B,E,BI,A,AS,S,...,0.628843,0.677765,0.624935,0.555306,0.242424,0.700829,0.531728,0.528427,0.922645,0.5
199997,499987,A,L,D,A,H,BI,A,AN,J,...,0.803348,0.324762,0.665624,0.488447,0.853213,0.578641,0.811941,0.537106,0.531758,0.5
199998,499994,A,K,A,C,F,BI,A,R,BM,...,0.820635,0.561449,0.797434,0.555089,0.746532,0.369986,0.438712,0.715524,0.381978,0.5
199999,499998,A,K,A,A,E,BI,C,AO,BM,...,0.270483,0.581868,0.218993,0.553284,0.565213,0.378355,0.547927,0.273595,0.448016,0.5